### ISSUE TITLE
Any类型接收不到

### ISSUE THREAD

**Issue by Denny-w** [imiphp/imi-grpc#3]
客户端
![image](https://user-images.githubusercontent.com/25193846/73825157-6d746580-4836-11ea-8684-97b6eb8fb2d9.png)
![image](https://user-images.githubusercontent.com/25193846/73825167-7402dd00-4836-11ea-9204-ebaa5792e4ae.png)

服务端:
![image](https://user-images.githubusercontent.com/25193846/73825217-89780700-4836-11ea-81d5-29b38c149145.png)
![image](https://user-images.githubusercontent.com/25193846/73825223-8da42480-4836-11ea-9193-0327209baab4.png)
![image](https://user-images.githubusercontent.com/25193846/73825248-998fe680-4836-11ea-9fcc-b7d12b10f61a.png)

服务端接收到获取到是`null`

**Comment by Yurunsoft** [comment]
```php
$anyData = new Any();
$data = new XXX();
$anyData->pack($data);
```

应该 set 的是`Any`对象

`pack()`方法返回值是`void`

**Comment by Denny-w** [comment]
麻烦了，看到了

**Comment by Denny-w** [comment]
想问一下就是，他接受到的不就已经是一个`Any`对象了，为什么还不能直接使用`unpack()`去吧里面的信息拿出来呢？

![image](https://user-images.githubusercontent.com/25193846/73828460-3d2fc580-483c-11ea-81c5-be81544702bf.png)

![image](https://user-images.githubusercontent.com/25193846/73828355-0d80bd80-483c-11ea-90aa-c48fac8aec93.png)

**Comment by Yurunsoft** [comment]
Any我这边项目也用了，没有这个问题，你看下客户端代码是否写对了

**Comment by Denny-w** [comment]
![image](https://user-images.githubusercontent.com/25193846/73829408-d7443d80-483d-11ea-8fda-4a2a1cbf6471.png)
![image](https://user-images.githubusercontent.com/25193846/73829442-e75c1d00-483d-11ea-8744-1e177c8d8ca2.png)

我按照刚才的方法重新`set`进去了，然后拿到这个对象了，没搞出来。。

**Comment by Yurunsoft** [comment]
可以查一下报错信息，看看是什么情况。这些都是 gRPC 的代码，跟 imi 关系不大
